#!/bin/bash
con=$1

#nsenter --target `docker inspect --format {% raw %}{{.State.Pid}}{% endraw %} $1` --mount --uts --ipc --net --pid bash
docker exec -it $con bash
if [ $? -gt 0 ] ; then
docker exec -it $con sh
fi
